name: HeroicDeath
main: com.herocraftonline.squallseed31.heroicdeath.HeroicDeath
version: 1.10.0
description: Minecraft plugin for Bukkit that announces player deaths. (modified version by BetaMC)
author: SquallSeeD31, SvGaming234